apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "torrent-http-proxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "torrent-http-proxy.name" . }}
    helm.sh/chart: {{ include "torrent-http-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "torrent-http-proxy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "torrent-http-proxy.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "torrent-http-proxy.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          env:
            - name: JOB_NODE_AFFINITY_KEY
              value: "{{ .Values.jobNodeAffinity.key }}"
            - name: JOB_NODE_AFFINITY_VALUE
              value: "{{ .Values.jobNodeAffinity.value }}"
            - name: SEEDER_IMAGE
              value: "{{ .Values.seeder.image }}"
            - name: SEEDER_CPU_REQUESTS
              value: "{{ .Values.seeder.cpu.requests }}"
            - name: SEEDER_CPU_LIMITS
              value: "{{ .Values.seeder.cpu.limits }}"
            - name: SEEDER_GRACE
              value: "{{ .Values.seeder.grace }}"
            - name: TRANSCODER_IMAGE
              value: "{{ .Values.transcoder.image }}"
            - name: TRANSCODER_CPU_REQUESTS
              value: "{{ .Values.transcoder.cpu.requests }}"
            - name: TRANSCODER_CPU_LIMITS
              value: "{{ .Values.transcoder.cpu.limits }}"
            - name: TRANSCODER_GRACE
              value: "{{ .Values.transcoder.grace }}"
            - name: WEB_ORIGIN_HOST_REDIRECT_FLAG
              value: "{{ .Values.redirect.enabled }}"
            - name: WEB_ORIGIN_HOST_REDIRECT_PREFIX_FLAG
              value: "{{ .Values.redirect.prefix }}"
            - name: USE_SNAPSHOT
              value: "{{ .Values.snapshot.enabled }}"
            - name: AWS_ACCESS_KEY_ID
              value: "{{ .Values.aws.accessKeyId }}"
            - name: AWS_SECRET_ACCESS_KEY
              value: "{{ .Values.aws.secretAccessKey }}"
            - name: AWS_BUCKET
              value: "{{ .Values.aws.bucket }}"
            - name: AWS_ENDPOINT
              value: "{{ .Values.aws.endpoint }}"
            - name: AWS_REGION
              value: "{{ .Values.aws.region }}"
            - name: AWS_BUCKET_SPREAD
              value: "{{ .Values.aws.bucketSpread }}"
            - name: AWS_NO_SSL
              value: "{{ .Values.aws.noSSL }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: httpprobe
              containerPort: 8081
              protocol: TCP
            - name: grpc
              containerPort: 50051
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /liveness
              port: httpprobe
          readinessProbe:
            httpGet:
              path: /readiness
              port: httpprobe
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
