{{- if .Values.ingressGRPC.enabled -}}
{{- $fullName := include "torrent-http-proxy.fullname" . -}}
{{- $ingressPaths := .Values.ingressGRPC.paths -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-grpc
  labels:
    app.kubernetes.io/name: {{ include "torrent-http-proxy.name" . }}
    helm.sh/chart: {{ include "torrent-http-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingressGRPC.annotations }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingressGRPC.tls }}
  tls:
  {{- range .Values.ingressGRPC.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingressGRPC.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
	{{- range $ingressPaths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: grpc
	{{- end }}
  {{- end }}
{{- end }}
