image:
  repository: webtor/torrent-web-cache
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

aws:
  accessKeyId: ""
  secretAccessKey: ""
  bucket: ""
  bucketSpread: ""
  endpoint: ""
  region: ""

service:
  type: ClusterIP
  port: 80
  topologyKeys: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}