image:
  repository: webtor/torrent-web-cache
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

update:
  maxUnavailable: 1

preload:
  cacheSize: 10Gi

persistence:
  enabled: true
  size: 20Gi

aws:
  accessKeyId: ""
  secretAccessKey: ""
  bucket: ""
  bucketSpread: ""
  endpoint: ""
  region: ""
  noSSL: ""

service:
  type: ClusterIP
  port: 80
  topologyKeys: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}