replicaCount: 2

image:
  repository: webtor/magnet2torrent
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
