# Default values for webtor-web-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: webtor/torrent-store
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}