image:
  repository: webtor/torrent-http-proxy
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

secret: ""
jobNodeAffinity:
  key: ""
  value: ""

redirect:
  enabled: ""
  prefix: "abra--"

seeder:
  image: webtor/torrent-web-seeder:latest
  cpu:
    requests: ""
    limits: ""

transcoder:
  image: webtor/content-transcoder:latest
  cpu:
    requests: ""
    limits: ""

clients: {}

rbac:
  create: true

service:
  type: ClusterIP
  port: 80
  topologyKeys: []

ingress:
  enabled: false
  annotations: {}
  paths: []
  hosts: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}