image:
  repository: webtor/torrent-http-proxy
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

secret: ""
jobNodeAffinity:
  key: ""
  value: ""

redirect:
  enabled: ""
  prefix: "abra--"

seeder:
  image: webtor/torrent-web-seeder:latest
  grace: 600
  cpu:
    requests: ""
    limits: ""

transcoder:
  image: webtor/content-transcoder:latest
  grace: 600
  cpu:
    requests: ""
    limits: ""

snapshot:
  enabled: false

aws:
  accessKeyId: ""
  secretAccessKey: ""
  bucket: ""
  endpoint: ""
  region: ""
  bucketSpread: ""
  noSSL: ""

clients: {}

rbac:
  create: true

service:
  type: ClusterIP
  ports: 
    http: 80
    grpc: 50051
  topologyKeys: []

ingress:
  enabled: false
  annotations: {}
  paths: []
  hosts: []
  tls: []

ingressGRPC:
  enabled: false
  annotations: {}
  paths: []
  hosts: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}