image:
  repository: webtor/torrent-http-proxy
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

secret: ""
jobNodeAffinity:
  key: ""
  value: ""

jobRequestAffinity: false

promAddr: ""

node:
  cpu:
    high: ""
    low: ""
  bandwidth:
    high: ""
    low: ""
  network:
    iface: ""

redirect:
  enabled: ""
  prefix: "abra--"
  addressType: "ExternalIP"

seeder:
  image: webtor/torrent-web-seeder:latest
  grace: 600
  cpu:
    requests: ""
    limits: ""

transcoder:
  image: webtor/content-transcoder:latest
  grace: 600
  cpu:
    requests: ""
    limits: ""

snapshot:
  enabled: false
  startThreshold: 0.5
  startFullDownloadThreshold: 0.75
  torrentSizeLimit: 10
  downloadRatio: 2.0

aws:
  accessKeyId: ""
  secretAccessKey: ""
  bucket: ""
  endpoint: ""
  region: ""
  bucketSpread: ""
  noSSL: ""

clients: {}

rbac:
  create: true

service:
  type: ClusterIP
  ports: 
    http: 80
    grpc: 50051
  topologyKeys: []

ingress:
  enabled: false
  annotations: {}
  paths: []
  hosts: []
  tls: []

ingressGRPC:
  enabled: false
  annotations: {}
  paths: []
  hosts: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}